# MYSQL Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/vaccine_portal
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
# Swagger
springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html
  
